# Generated by Django 5.2.4 on 2025-08-18 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0005_alter_lesson_options_remove_lesson_order_and_more'),
        ('practice', '0002_userskillprogress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attempt',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='practicequestion',
            old_name='explanation_text',
            new_name='explanation',
        ),
        migrations.AlterUniqueTogether(
            name='attempt',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='practicequestion',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='selected',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='practicequestion',
            name='choice_a',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='practicequestion',
            name='choice_b',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='practicequestion',
            name='choice_c',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='practicequestion',
            name='choice_d',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='practicequestion',
            name='correct_answer',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='skillset',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='skillset',
            name='related_standards',
            field=models.ManyToManyField(blank=True, to='curriculum.standard'),
        ),
        migrations.AlterField(
            model_name='skillset',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
