# Generated by Django 5.2.4 on 2025-07-22 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_topic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='domain',
            options={'ordering': ['grade__level', 'sort_order', 'name']},
        ),
        migrations.AddField(
            model_name='domain',
            name='sort_order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
