# Generated by Django 5.2.4 on 2025-08-04 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0003_alter_domain_options_domain_sort_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='source_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='topic',
            unique_together={('standard', 'title')},
        ),
    ]
