# Generated by Django 5.2.4 on 2025-08-18 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0002_gardenstate_badge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loginstreak',
            old_name='current_streak',
            new_name='count',
        ),
        migrations.RenameField(
            model_name='loginstreak',
            old_name='last_login',
            new_name='last_login_day',
        ),
        migrations.RemoveField(
            model_name='loginstreak',
            name='longest_streak',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='last_update',
        ),
        migrations.AlterField(
            model_name='badge',
            name='badge_type',
            field=models.CharField(choices=[('streak_7', '7-Day Streak'), ('streak_30', '30-Day Streak'), ('all_skills_grade', 'All Skills (Grade)')], max_length=50),
        ),
        migrations.AlterField(
            model_name='gardenstate',
            name='health_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gardenstate',
            name='visual_theme',
            field=models.CharField(default='spring', max_length=50),
        ),
    ]
